version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nft-transfer-events"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p2jj8mhlfiu1"
s3_prefix = "nft-transfer-events"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "StageName=\"dev\" ERC721AddressParameter=\"0x0A10eb7aE39BbB66a86138443847D5fA1Fe60503\""
