version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nft-transfer-view"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p2jj8mhlfiu1"
s3_prefix = "nft-transfer-view"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
