AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nft-transfer-events

  Sample SAM Template for nft-transfer-events monitorint and visualizing
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NFTTransferEventsViewFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nft-lambdas/
      Handler: view.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        # Give the Lambda service access to poll DynamoDB Stream
        - AmazonDynamoDBFullAccess
      Events:
        NFTTransferEventsView:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /nft-transfers
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
        - view.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NFTTransferEventsViewApi:
    Description: "API Gateway endpoint URL for Prod stage for NFT Transfer Events View function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/nft-transfers/"
  NFTTransferEventsViewFunction:
    Description: "NFT Transfer Events View Lambda Function ARN"
    Value: !GetAtt NFTTransferEventsViewFunction.Arn
  NFTTransferEventsViewFunctionIamRole:
    Description: "Implicit IAM Role created for NFT Transfer Events View function"
    Value: !GetAtt NFTTransferEventsViewFunctionRole.Arn
